project:
  type: website
  resources:
    - robots.txt
website:
  title: "Documentation Platform"
  bread-crumbs: false
  navbar:
    background: white
    logo: images/client-logo.png
    pinned: true
    search: true
    right:
      - text: |
          <img src="/images/my-logo.png" style="height: 30px; vertical-align: middle;" alt="IEP Logo">
        href: "https://example.com"
  page-footer:
    left: "Powered by Your Organization"
  sidebar:
    style: "docked"
    background: white
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Customization"
        href: customization.qmd
      - text: "Styling"
        href: styling.qmd

format:
  html:
    grid:
      sidebar-width: 280px
      body-width: 1000px
      margin-width: 250px
      gutter-width: 3rem
    theme:
      - cosmo
    css:
      - styles.css
    toc: true



