project:
  type: website

website:
  title: "Documentation Platform"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: getting-started.qmd
        text: Get Started
      - href: documentation.qmd
        text: Docs
      - href: tutorials.qmd
        text: Tutorials
      - href: api-reference.qmd
        text: API
      - href: blog.qmd
        text: Blog
      - href: about.qmd
        text: About

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



